[[main]]
  identifier = "archive"
  name = "archive"
  url = "archive"
  weight = 1


[[main]]
  identifier = "moments"
  name = "moments"
  url = "moments"
  weight = 3



[[main]]
  identifier = "publication"
  name = "publications"
  url = "publication"
  weight = 5



[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 6
