[[main]]
  identifier = "archive"
  name = "archive"
  url = "archive"
  weight = 1


[[main]]
  identifier = "moments"
  name = "moments"
  url = "moments"
  weight = 3



[[main]]
  identifier = "publication"
  name = "publications"
  url = "publication"
  weight = 5


[[main]]
  identifier = "others"
  name = "others"
  weight = 4

[[main]]
  parent = "others"
  name = "flappy-bird"
  url = "posts/others/flappy-bird-with-machine-learning/"


[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 6
