[[main]]
  identifier = "archive"
  name = "archive"
  url = "archive"
  weight = 1


[[main]]
  identifier = "posts"
  name = "posts"
  url = "posts"
  weight = 2

[[main]]
  identifier = "moments"
  name = "moments"
  url = "moments"
  weight = 3
    
[[main]]
  identifier = "cloud"
  name = "cloud"
  weight = 4

[[main]]
  parent = "cloud"
  name = "olaindex"
  url = "https://one.xunhs.cyou"


[[main]]
  parent = "cloud"
  name = "tianyi"
  url = "https://tianyi.xunhs.cyou"

[[main]]
  parent = "cloud"
  name = "cloudreve"
  url = "https://cloudreve.xunhs.cyou"

[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 5