[[main]]
  identifier = "archive"
  name = "archive"
  url = "archive"
  weight = 1


[[main]]
  identifier = "posts"
  name = "posts"
  url = "posts"
  weight = 2

[[main]]
  identifier = "moments"
  name = "moments"
  url = "moments"
  weight = 3

[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 5